runtime: php
env: flex

runtime_config:
  document_root: .

#[START gae_flex_postgres_env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    POSTGRES_USER: styl
    POSTGRES_PASSWORD: 1234
    POSTGRES_DSN: pgsql:dbname=DATABASE;host=/cloudsql/mysql
#[END gae_flex_postgres_env]

#[START gae_flex_postgres_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "mysql"
#[END gae_flex_postgres_settings]
